describe('Tusmo Game', () => {
  it('Visit', () => {
    cy.visit('http://localhost:3000')
  })

  it('check word is init',  () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', 'https://trouve-mot.fr/api/random/1', { fixture: 'words.json' })
    cy.wait(1000)
    cy.get('#input_0').should('have.text', '_')
    cy.get('#input_1').should('have.text', '_')
    cy.get('#input_2').should('have.text', '_')
    cy.get('#input_3').should('have.text', '_')
  })

  it('keypress a letter set letter in span',  () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', 'https://trouve-mot.fr/api/random/1', { fixture: 'words.json' })
    cy.wait(1000)
    cy.get('#input_0').should('have.text', '_')
    cy.get('body').type('u')
    cy.get('#input_0').should('have.text', 'U')
  })

  it('keypress a word set letter in span',  () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', 'https://trouve-mot.fr/api/random/1', { fixture: 'words.json' })
    cy.wait(1000)
    cy.get('#input_0').should('have.text', '_')
    cy.get('body').type('uais')
    cy.get('#input_0').should('have.text', 'U')
    cy.get('#input_1').should('have.text', 'A')
    cy.get('#input_2').should('have.text', 'I')
    cy.get('#input_3').should('have.text', 'S')
  })

  it('keypress delete key delete letter in span',  () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', 'https://trouve-mot.fr/api/random/1', { fixture: 'words.json' })
    cy.wait(1000)
    cy.get('#input_0').should('have.text', '_')
    cy.get('body').type('u')
    cy.get('#input_0').should('have.text', 'U')
    cy.get('body').type('{backspace}')
    cy.get('#input_0').should('have.text', '_')
  })

  it('if word have 4 letter and user type 6 letter just show the first 4 letter',  () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', 'https://trouve-mot.fr/api/random/1', { fixture: 'words.json' })
        cy.wait(1000)
    cy.get('#input_0').should('have.text', '_')
    cy.get('body').type('usmoouaisEtoile')
    cy.get('#input_0').should('have.text', 'U')
    cy.get('#input_1').should('have.text', 'S')
    cy.get('#input_2').should('have.text', 'M')
    cy.get('#input_3').should('have.text', 'O')
  })
  
  it('click on validate button and show the word',   () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', 'https://trouve-mot.fr/api/random/1', { fixture: 'words.json' })
    cy.wait(1000)
    cy.get('#input_0').should('have.text', '_')
    cy.get('body').type('usmo')
    cy.get('#validate_button').click()
    cy.get('#result_word_0 > #result_letter_0').should('have.class', 'bg-red-500')
    cy.get('#result_word_0 >#result_letter_1').should('have.class', 'bg-red-500')
    cy.get('#result_word_0 >#result_letter_2').should('have.class', 'bg-yellow-500')
    cy.get('#result_word_0 >#result_letter_3').should('have.class', 'bg-blue-500')
    cy.get('#result_word_0 > #result_letter_4').should('have.class', 'bg-yellow-500')
  })

  it('click on validate button and show the word but with history',   () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', 'https://trouve-mot.fr/api/random/1', { fixture: 'words.json' })
    cy.wait(1000)
    cy.get('#input_0').should('have.text', '_')
    cy.get('body').type('usmo')
    cy.get('#validate_button').click()
    cy.get('body').type('hles')
    cy.get('#validate_button').click()
    cy.get('#result_word_0 > #result_letter_0').should('have.class', 'bg-red-500')
    cy.get('#result_word_0 > #result_letter_1').should('have.class', 'bg-red-500')
    cy.get('#result_word_0 > #result_letter_2').should('have.class', 'bg-yellow-500')
    cy.get('#result_word_0 > #result_letter_3').should('have.class', 'bg-blue-500')
    cy.get('#result_word_0 > #result_letter_4').should('have.class', 'bg-yellow-500')
    cy.get('#result_word_1 > #result_letter_0').should('have.class', 'bg-red-500')
    cy.get('#result_word_1 > #result_letter_1').should('have.class', 'bg-blue-500')
    cy.get('#result_word_1 > #result_letter_2').should('have.class', 'bg-blue-500')
    cy.get('#result_word_1 > #result_letter_3').should('have.class', 'bg-blue-500')
    cy.get('#result_word_1 > #result_letter_4').should('have.class', 'bg-red-500')
  })

  it('send message when the word is found',   () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', 'https://trouve-mot.fr/api/random/1', { fixture: 'words.json' })
    cy.wait(1000)
    cy.get('#input_0').should('have.text', '_')
    cy.get('body').type('usmo')
    cy.get('#validate_button').click()
    cy.get('body').type('hles')
    cy.get('#validate_button').click()
    cy.get('body').type('uais')
    cy.get('#validate_button').click()
    cy.get('#error_label').should('have.text', 'Vous avez trouvé le mot !')
  })

  it('show message when the word is not found', () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', 'https://trouve-mot.fr/api/random/1', { fixture: 'words.json' })
    cy.wait(1000)
    cy.get('#input_0').should('have.text', '_')
    cy.get('body').type('usmo')
    cy.get('#validate_button').click()
    cy.get('body').type('hles')
    cy.get('#validate_button').click()
    cy.get('body').type('hfls')
    cy.get('#validate_button').click()
    cy.get('body').type('popo')
    cy.get('#validate_button').click()
    cy.get('body').type('ytrp')
    cy.get('#validate_button').click()
    cy.get('body').type('jfdl')
    cy.get('#validate_button').click()
    cy.get('#error_label').should('have.text', 'Vous avez épuisé vos essais. Le mot était OUAIS.')
  })
})